import chisel3._
import chiseltest._
import org.scalatest.flatspec.AnyFlatSpec

// The simplest parameterization of all: a bit width handed to the constructor.
// There is nothing to observe at run time - the parameter shapes the hardware at
// GENERATION time - so the test instead checks the one thing the width is
// visible in: the sum wraps around modulo 2^n.
class ParamAdderTest extends AnyFlatSpec with ChiselScalatestTester {

  // One test per width, generated by a Scala `for` loop over the parameter: the
  // same trick the generator itself uses, applied to the test bench.
  for (n <- Seq(4, 8, 16)) {
    val mask = (1 << n) - 1

    s"ParamAdder($n)" should s"add modulo 2^$n" in {
      test(new ParamAdder(n)) { dut =>
        val cases = Seq((0, 0), (1, 2), (mask, 0), (mask, 1), (mask, mask), (mask / 2, mask / 2 + 1))
        for ((a, b) <- cases) {
          dut.io.a.poke(a.U)
          dut.io.b.poke(b.U)
          // An n-bit `+` keeps n bits: the carry out is dropped.
          dut.io.c.expect(((a + b) & mask).U)
        }
      }
    }
  }

  // UseAdder instantiates the SAME generator twice, at 8 and at 16 bits, and ORs
  // the two results:  io.res := add16.io.c | add8.io.c
  // Both adders get the full 16-bit x/y, but add8's ports are only 8 bits wide,
  // so the connection truncates - which is exactly what makes the two instances
  // distinguishable from outside.
  "UseAdder" should "combine an 8-bit and a 16-bit instance of the same generator" in {
    test(new UseAdder) { dut =>
      def check(x: Int, y: Int): Unit = {
        val sum16 = (x + y) & 0xffff
        val sum8 = ((x & 0xff) + (y & 0xff)) & 0xff
        dut.io.x.poke(x.U)
        dut.io.y.poke(y.U)
        dut.io.res.expect((sum16 | sum8).U)
      }

      check(0, 0)
      check(1, 2)         // both adders agree: 3
      check(0x00ff, 1)    // the 8-bit adder wraps to 0x00, the 16-bit one gives 0x0100
      check(0x1234, 0x00ff)
      check(0xffff, 1)    // the 16-bit adder wraps too: 0x0000 | 0x00 = 0
      check(0xabcd, 0x1234)
    }
  }
}
