import chisel3._
import chisel3.util._

// The four minimum-search variants of FunctionalMin.scala, one per module, so
// that the SystemVerilog generated by each can be compared. See MinDemo below
// and Section 10.6.1.
//
// Same logic as in FunctionalMin, just isolated: FunctionalMin builds all four
// at once, which makes its emitted Verilog impossible to read variant by variant.

// (a) minimum value only: reduceTree with a Mux.
class MinValueOnly(n: Int, w: Int) extends Module {
  val io = IO(new Bundle {
    val in = Input(Vec(n, UInt(w.W)))
    val min = Output(UInt(w.W))
  })

  io.min := io.in.reduceTree((x, y) => Mux(x < y, x, y))
}

// (b) value AND index, using a Bundle to carry both, reduceTree.
class MinBundle(n: Int, w: Int) extends Module {
  val io = IO(new Bundle {
    val in = Input(Vec(n, UInt(w.W)))
    val min = Output(UInt(w.W))
    val idx = Output(UInt(8.W))
  })

  class Two extends Bundle {
    val v = UInt(w.W)
    val idx = UInt(8.W)
  }
  val vecTwo = Wire(Vec(n, new Two()))
  for (i <- 0 until n) {
    vecTwo(i).v := io.in(i)
    vecTwo(i).idx := i.U
  }
  val res = vecTwo.reduceTree((x, y) => Mux(x.v < y.v, x, y))

  io.min := res.v
  io.idx := res.idx
}

// (c) value AND index, using Scala tuples + zipWithIndex + reduce (a CHAIN).
class MinTuple(n: Int, w: Int) extends Module {
  val io = IO(new Bundle {
    val in = Input(Vec(n, UInt(w.W)))
    val min = Output(UInt(w.W))
    val idx = Output(UInt(8.W))
  })

  val resFun = io.in.zipWithIndex
    .map((x) => (x._1, x._2.U))
    .reduce((x, y) => (Mux(x._1 < y._1, x._1, y._1),
      Mux(x._1 < y._1, x._2, y._2)))

  io.min := resFun._1
  io.idx := resFun._2
}

// (d) value AND index, using a MixedVec + reduceTree.
class MinMixedVec(n: Int, w: Int) extends Module {
  val io = IO(new Bundle {
    val in = Input(Vec(n, UInt(w.W)))
    val min = Output(UInt(w.W))
    val idx = Output(UInt(8.W))
  })

  val scalaVector = io.in.zipWithIndex
    .map((x) => MixedVecInit(x._1, x._2.U(8.W)))
  val resFun2 = VecInit(scalaVector)
    .reduceTree((x, y) => Mux(x(0) < y(0), x, y))

  io.min := resFun2(0)
  io.idx := resFun2(1)
}
